/**
 * TheLittleGuy store of global action names
 */

/* USER ACTIONS */
export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
export const UPDATE_USER = 'UPDATE_USER';

/* PROPERTY ACTIONS */
export const FETCH_ALL_PROPERTIES = 'FETCH_ALL_PROPERTIES';
export const EDIT_PROPERTY = 'EDIT_PROPERTY';
export const DELETE_PROPERTY = 'DELETE_PROPERTY';
export const ADD_PROPERTY = 'ADD_PROPERTY';

/* LANDLORD ACTIONS */
export const FETCH_MY_PROPERTIES = 'FETCH_MY_PROPERTIES';
export const ADD_MY_PROPERTY = 'ADD_MY_PROPERTY';
export const EDIT_MY_PROPERTY = 'EDIT_MY_PROPERTY';
export const DELETE_MY_PROPERTY = 'DELETE_MY_PROPERTY';

/* APPLICATION ACTIONS */
export const FETCH_APPLICATIONS = 'FETCH_APPLICATIONS';
export const EDIT_APPLICATIONS = 'EDIT_APPLICATIONS';